### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by robsonfelix** [Metalab/behringer_xr18_hass#1]
I am using the LAG version of Home Assistant, and I proceeded according to your instructions but the installation dialog never comes up but gives me this error instead.

Would you help?

**Comment by anlumo** [comment]
What is the LAG version? OS, Container, Core, or Supervised? Obviously, it's impossible to Google for “lag” and find anything meaningful.

To debug this, you have to find your Home Assistant log. This can usually be found in Settings -> System -> Logs -> Load full logs (big button at the bottom). There should be a python exception with stacktrace somewhere there.

**Comment by robsonfelix** [comment]
LAG = Latest and Greatest. In my case:

Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Comment by robsonfelix** [comment]
The error I see in the log is: "homeassistant.requirements.RequirementsNotFound: Requirements for behringer_xr18 not found: ['aiohttp==3.8.4']."

**Comment by robsonfelix** [comment]
I made it work by changing the aiohttp==3.8.4 to aiohttp>=3.8.4....

I was able to install and set it up.

My Home Assistant instance is now REALLY SLOW, and the entities although visible are not showing any value and now 'not available'.

This is the error message I see in the log:

Log details (ERROR)
Logger: homeassistant.helpers.integration_platform
Source: helpers/integration_platform.py:50
First occurred: 7:00:57 PM (10 occurrences)
Last logged: 7:03:02 PM

Unexpected error importing behringer_xr18/system_health.py
Unexpected error importing behringer_xr18/cast.py
Unexpected error importing behringer_xr18/significant_change.py
Unexpected error importing behringer_xr18/energy.py
Unexpected error importing behringer_xr18/hardware.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.behringer_xr18_hass.diagnostics'

**Comment by robsonfelix** [comment]
I also see this in the error log:

Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 7:01:29 PM (2 occurrences)
Last logged: 7:01:29 PM

Error setting up entry Behringer XR18 Mixer (XR18-E2-1D-35) for switch
Error setting up entry Behringer XR18 Mixer (XR18-E2-1D-35) for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 83, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
